VideogameShop/Controllers/MessaggiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VideogameShop.Database;
using VideogameShop.Models;

namespace VideogameShop.Controllers
{
    public class MessaggiController : Controller
    {
        [Route("/CasellaMessaggi")]
        public IActionResult Index()
        {
            VideogameContext db = new();
            List<MessaggioPrivato> ListaMessaggi = db.Messaggi.Where(m=>m.Destinatario.UserName==User.Identity.Name).Include(u=>u.Mittente).ToList();
            return View(ListaMessaggi);
        }

        [HttpGet]
        public IActionResult NuovoMessaggio()
        {
            MessaggioPrivato messaggio = new();
            return View(messaggio);
        }

        [HttpPost]
        public IActionResult NuovoMessaggio(MessaggioPrivato formdata)
        {
            using (VideogameContext db = new VideogameContext())
            {
                if (!ModelState.IsValid)
                {
                    return View(formdata);
                }
                formdata.Mittente = db.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
                formdata.Destinatario = db.Users.Where(u => u.UserName == formdata.Destinatario.UserName).FirstOrDefault();
                formdata.DataOra = DateTime.Now;
                db.Messaggi.Add(formdata);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Messaggio(int id)
        {
            using VideogameContext db = new();
            MessaggioPrivato messaggio = db.Messaggi.Where(m => m.Id == id).Include(m=>m.Mittente).FirstOrDefault();
            messaggio.MessaggioLetto = true;
            db.SaveChanges();
            return View(messaggio);
        }

        public IActionResult EliminaMessaggio(int id)
        {
            using VideogameContext db = new();
            MessaggioPrivato messaggio = db.Messaggi.Where(m => m.Id == id).Include(m => m.Mittente).FirstOrDefault();
            db.Remove(messaggio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

}

VideogameShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Negozio Videogiochi</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link runat="server" rel="shortcut icon" href="/lib/mushroom_icon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="/lib/mushroom_icon.ico" image /ico" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VideogameShop.styles.css" asp-append-version="true" />
</head>
<body style="background-color: #1a1a1a">
    <header class=" sticky-top">
        <nav class="navbar navbar-light" id="navbar">
            <div class="container-fluid">
                <button class="btn testogrande" style="background-color: #1a1a1a; color: #a8a04d" type="button" data-bs-toggle="offcanvas"
                        data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">
                    Imperivm Games
                </button>

                <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
                     aria-labelledby="offcanvasWithBothOptionsLabel"
                     style="background-image: url(/img/background-navbar.jpg); background-repeat: repeat;">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title text-light titolo" id="offcanvasWithBothOptionsLabel">Imperivm Games</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">

                        <ul class="nav nav-pills flex-column mb-auto">
                            <li style="margin-left:0" class="nav-item my-3 testoCarosello">
                                <a asp-controller="Home" asp-action="Index" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#home"></use>
                                    </svg>
                                    Home
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("play","home")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#grid"></use>
                                    </svg>
                                    Giochi Playstation
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("pc","home")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#people-circle"></use>
                                    </svg>
                                    Giochi PC
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("xbox","home")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#people-circle"></use>
                                    </svg>
                                    Giochi XBOX
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("nin","home")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#people-circle"></use>
                                    </svg>
                                    Giochi Nintendo
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("Index","Admin")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#people-circle"></use>
                                    </svg>
                                    Area Amministrazione
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="testo ">

                    <div>
                        <a asp-controller="Messaggi" asp-action="Index"><img width="20%" src="~/img/letteraMessaggi.png" /></a>
                        <a asp-controller="Home" asp-action="VistaCarrello">
                            <p class="text-light">Carrello: @Carrello.CarrelloCorrente.ProdottiAcquistati.Count() </p>
                        </a>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
        </nav>

    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="border-top footer text-light">
        <div class="container">
            &copy; 2023 - VideogameShop
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VideogameShop/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Negozio Videogiochi</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link runat="server" rel="shortcut icon" href="/lib/mushroom_icon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="/lib/mushroom_icon.ico" image /ico" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VideogameShop.styles.css" asp-append-version="true" />
</head>
<body style="background-color: #1a1a1a; color: white;">
    <header class=" sticky-top">
        <nav class="navbar navbar-light" id="navbar">
            <div class="container-fluid">
                <button class="btn testogrande" style="background-color: #1a1a1a; color: #a8a04d" type="button" data-bs-toggle="offcanvas"
                        data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">
                    Imperivm Games
                </button>

                <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
                     aria-labelledby="offcanvasWithBothOptionsLabel"
                     style="background-image: url(/img/background-navbar.jpg); background-repeat: repeat;">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title text-light titolo" id="offcanvasWithBothOptionsLabel">Imperivm Games</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">

                        <ul class="nav nav-pills flex-column mb-auto">
                            <li style="margin-left:0" class="nav-item my-3 testoCarosello">
                                <a asp-controller="Home" asp-action="Index" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#home"></use>
                                    </svg>
                                    Home
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("play","home")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#grid"></use>
                                    </svg>
                                    Giochi Playstation
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("pc","home")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#people-circle"></use>
                                    </svg>
                                    Giochi PC
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("xbox","home")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#people-circle"></use>
                                    </svg>
                                    Giochi XBOX
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("nin","home")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#people-circle"></use>
                                    </svg>
                                    Giochi Nintendo
                                </a>
                            </li>
                            <li style="margin-left:0" class="my-3 testoCarosello">
                                <a href="@Url.Action("Index","Admin")" class="nav-link link-dark text-light testo">
                                    <svg class="bi pe-none me-2" width="16" height="16">
                                        <use xlink:href="#people-circle"></use>
                                    </svg>
                                    Area Amministrazione
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="testo ">

                    <div>
                        <a asp-controller="Messaggi" asp-action="Index"><img width="20%" src="~/img/letteraMessaggi.png" /></a>
                        <a asp-controller="Home" asp-action="VistaCarrello">
                            <p class="text-light">Carrello: @Carrello.CarrelloCorrente.ProdottiAcquistati.Count() </p>
                        </a>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>

    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="border-top footer text-light">
        <div class="container">
            &copy; 2023 - VideogameShop
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>